name: 🐍 Update Snake

on:
  push:
    branches:
      - main
  schedule:
    # toda segunda-feira à meia-noite UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar Snake SVG (dark)
        uses: Platane/snk/svg-only@v3
        with:
          # usa o seu usuário automaticamente
          github_user_name: ${{ github.repository_owner }}
          # gera somente o SVG dark no diretório `output/`
          outputs: |
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit do SVG gerado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "github-actions@github.com"
          message: "chore: atualizar snake grid"
