name: 🐍 Update Snake

on:
  schedule:
    # toda segunda-feira às 00:00 UTC (ajuste como quiser)
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar grid snake SVG
        uses: joao1015/github-contribution-grid-snake@v1

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: dark              # ou light
          output: output           # pasta onde vai salvar o .svg

      - name: Commit do SVG gerado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "github-actions@github.com"
          message: "chore: atualizar snake grid"
